Repository takuma-ru/CupMENWeb, pull requests merged in 2021-01, with the labels that each got.

#7 カップ麺の商品情報の追加
  assets/json/Area_item.json
  assets/json/myojo_item.json
  assets/json/sanyoo_item.json
  pages/Sanyoo.vue
Labels: 新機能

#8 Addjson
  assets/json/cvs.json
  assets/json/nissin.json
  assets/json/overseas.json
  components/article_normal.vue
Labels: 修正

#11 商品コンポーネントの追加、JSONファイルを少し変更
  assets/img/components/Hot.svg
  assets/img/components/RamenFrame.svg
  assets/img/components/SobaFrame.svg
  assets/img/components/SonotaFrame.svg
  assets/img/components/UdonFrame.svg
  assets/img/components/YakisobaFrame.svg
  assets/json/nissin.json
  assets/json/overseas.json
  components/ArticleNormal.vue
  components/ArticleOverseas.vue
  components/ArticleSpecial.vue
  components/article_normal.vue
Labels: 修正, 新機能

#12 Top
  assets/img/cupnoodle.jpg
  assets/json/top_link.json
  components/AboutCompany.vue
  components/Top_CompanyLink.vue
  nuxt.config.js
  pages/index.vue
  static/favicon.svg
  store/index.js
Labels: 新機能

#13 Update default.vue, Fix nuxt.config
  assets/img/background.svg
  layouts/default.vue
  nuxt.config.js
Labels: 修正, 新機能

#16 Nissin conveni overseas
  assets/img/conveni/eight.jpg
  assets/img/conveni/five.jpg
  assets/img/conveni/four.jpg
  assets/img/conveni/nine.png
  assets/img/conveni/one.jpg
  assets/img/conveni/seven.jpg
  assets/img/conveni/six.jpg
  assets/img/conveni/ten.jpg
  assets/img/conveni/three.jpg
  assets/img/conveni/two.jpg
  assets/json/cvs.json
  components/ArticleNormal.vue
  components/ArticleOverseas.vue
  components/ArticleSpecial.vue
Labels: 修正

#18 Nissin conveni overseas
  components/ArticleSpecial.vue
Labels: 修正

#19 Update ArticleSpecial.vue
  components/ArticleSpecial.vue
Labels: 修正

#21 サンヨー食品・ご当地カップ麺の仮実装　UIの修正
  assets/img/area/01.png
  assets/img/area/02.png
  assets/img/area/03.jpg
  assets/img/area/04.jpg
  assets/img/area/05.jpg
  assets/img/area/06.jpg
  assets/img/area/07.jpg
  assets/img/area/08.jpg
  assets/img/area/09.jpg
  assets/img/area/10.jpg
  assets/img/area/11.jpg
  assets/img/area/12.jpg
  assets/img/area/13.jpg
  assets/img/area/touhoku.svg
  assets/img/sanyoo/1903soydon1D.jpg
  assets/img/sanyoo/2002431101.jpg
  assets/img/sanyoo/2002432201.jpg
  assets/img/sanyoo/2003MAM01.jpg
  assets/img/sanyoo/2004otafuku.jpg
  assets/img/sanyoo/2008CSS10.jpg
  assets/img/sanyoo/2010WRM10_2.jpg
  assets/img/sanyoo/2011BTM06.jpg
  assets/img/sanyoo/2011CDU05.jpg
  assets/img/sanyoo/9af8d17220cfc0f35e6f9a96fa616cda.jpg
  assets/json/Area_item.json
  assets/json/sanyoo_item.json
  components/AboutCompany.vue
  components/Top_CompanyLink.vue
  nuxt.config.js
  pages/Area.vue
  pages/Sanyoo.vue
  pages/index.vue
  store/index.js
Labels: 修正, 新機能

#23 Update Sanyoo, Fix AboutCompany
  components/AboutCompany.vue
  pages/Sanyoo.vue
Labels: 修正

#24 Add Top img, Update Top
  assets/img/top.svg
  assets/img/top/09c851fdb12bfefcb409ce85849553ac_w.jpeg
  assets/img/top/18h_prbg001.jpg
  assets/img/top/2-19-1-768x557.jpg
  assets/img/top/49ecc2cf05109490dd4161da2c806062_w.jpeg
  assets/img/top/about_ttl_sp.jpg
  assets/img/top/banner-pc.png
  assets/img/top/cupnoodle.jpg
  assets/img/top/mv03.jpg
  assets/img/top/world-map-1748403_1280.png
  assets/json/top_link.json
  components/Top_CompanyLink.vue
  pages/Area.vue
  pages/index.vue
Labels: バグ, 修正, 新機能
